### ISSUE TITLE
Question on Contributing a Cookbook

### ISSUE THREAD

**Issue by cmdupuis3** [ProjectPythia/.github#39]
Hello, I'm trying to submit a new cookbook as per the guide [here](https://github.com/ProjectPythia/.github/blob/main/.github/CONTRIBUTING.md). However, I'm confused about how to merge my repo. Section 3.1 says to create a new branch (which I've done), and Section 3.7 says to submit a merge request, but it is not clear to me what I'm merging or where I'm merging it to. Am I merging my branch to my fork's main? My branch to Pythia's main? I'm really lost on this.

**Comment by dcamron** [comment]
Resolving elsewhere.
