### ISSUE TITLE
Updating the Cookbook Contributor's Guide before the summer hackathon

### ISSUE THREAD

**Issue by r-ford** [ProjectPythia/.github#47]
Before our 2023 hackathon, I think the [contributor's guide](https://github.com/ProjectPythia/.github/blob/main/.github/CONTRIBUTING.md) needs some updating. Here is a potential outline:

1. Data access (include a statement encouraging the use of freely-available data, with the option for some small files to be added to the cookbook)
1. Use the template (maybe just a few edits for clarity)
1. Develop your cookbook (How much detail should we include here? We may be able to just link our GitHub/Conda tutorials and otherwise assume the reader knows how to do this part.)
1. Pre-transfer checklist
    - [ ] Update README.md, including badge links
    - [ ] Make changes to _config.yml. These will show up on the card in the gallery.
        - [ ] title
        - [ ] author
        - [ ] description
        - [ ] thumbnail
        - [ ] tags
    - [ ] Add notebooks to _toc.yml (Table of contents)
    - [ ] Clear all notebook outputs
    - [ ] *Cookbook successfully builds using either GitHub Actions or the Pythia Binder*
1. Transfer to the ProjectPythia org (I think this part is mostly fine the way it is now.)
1. Add cookbook to gallery

---

Questions:
- How complete should a cookbook be before it gets transferred to this org? I think there should be at least one notebook that builds successfully using our infrastructure.
- Do we want to make the Pangeo Discourse the main way contributors let us know about their cookbooks? How about a Google Form?

**Comment by jukent** [comment]
@negin513 could you drop your thoughts on the contributor's guide in this issue?

**Comment by jukent** [comment]
Thanks for the contribution and the feedback @r-ford and @negin513
